### ISSUE TITLE
Sequence tag spacing issue

### ISSUE THREAD

**Issue by kingjacob** [Synbiota/GENtle2#107]
![screen shot 2014-03-14 at 4 15 35 pm](https://f.cloud.github.com/assets/806312/2422975/59ce64b2-ab94-11e3-8b65-c18ce5ebe0df.png)

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
