### ISSUE TITLE
short S amino acids (Serine) are highlighted in red instead of Xs (Stop)

### ISSUE THREAD

**Issue by depha** [Synbiota/GENtle2#174]
When Display Options are set to 1-letter amino acids, the "S" (serine) amino acids are shown as red, which is incorrect. Instead, the "X" (stop codon) should be red.

**Comment by DesireeSy** [comment]
This showed up in usability tests SPR 009-01 and 009-02.

**Comment by OkayDave** [comment]
Fixed in #185
