### ISSUE TITLE
reverse universal seq primer not found for this RDP circuit

### ISSUE THREAD

**Issue by DesireeSy** [Synbiota/GENtle2#194]
This is a circuit built from parts we're giving to iGEM teams. There's no reverse universal sequencing primer found.

[Can't seem to attach SYBIL files. I've cut and pasted this.]

TGAGGATTCTCACCAATAAAAAACGCCCGGCGGCAACCGAGCGTTCTGAACAAATCCAGATGGAGTTCTGAGGTCATTACTGGATCTATCAACAGGAGTCCAAGCGAGCTCGATATCAAATTACGCCCCGCCCTGCCACTCATCGCAGTACTGTTGTAATTCATTAAGCATTCTGCCGACATGGAAGCCATCACAAACGGCATGATGAACCTGAATCGCCAGCGGCATCAGCACCTTGTCGCCTTGCGTATAATATTTGCCCATGGTGAAAACGGGGGCGAAGAAGTTGTCCATATTGGCCACGTTTAAATCAAAACTGGTGAAACTCACCCAGGGATTGGCTGAGACGAAAAACATATTCTCAATAAACCCTTTAGGGAAATAGGCCAGGTTTTCACCGTAACACGCCACATCTTGCGAATATATGTGTAGAAACTGCCGGAAATCGTCGTGGTATTCACTCCAGAGCGATGAAAACGTTTCAGTTTGCTCATGGAAAACGGTGTAACAAGGGTGAACACTATCCCATATCACCAGCTCACCGTCTTTCATTGCCATACGAAATTCCGGATGAGCATTCATCAGGCGGGCAAGAATGTGAATAAAGGCCGGATAAAACTTGTGCTTATTTTTCTTTACGGTCTTTAAAAAGGCCGTAATATCCAGCTGAACGGTCTGGTTATAGGTACATTGAGCAACTGACTGAAATGCCTCAAAATGTTCTTTACGATGCCATTGGGATATATCAACGGTGGTATATCCAGTGATTTTTTTCTCCATTTTAGCTTCCTTAGCTCCTGAAAATCTCGATAACTCAAAAAATACGCCCGGTAGTGATCTTATTTCATTATGGTGAAAGTTGGAACCTCTTACGTGCCCGATCAACTCGAGTGCCACCTGACGTCTAAGAAACCAGAATTCTCATGACATTAACCTCCAGTAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGTTGTTCAGAACGCTCGGTCTTGCACACCGGGCGTTTTTTCTTTGTGAGTCCAGCGGCCGCGTGAGGTCAGATGCTGAACGTCGGGTCTCAGATGTTTACGGCTAGCTCAGTCCTAGGTACTATCGGCTGAGTACCTCACACAGGAAAGTGATGATGATCTGCCTTTGGGTCCTCTGTTTCGTCCTTTTCCCCTACTCCTTGTCCTATCCCGAGAGCTGGATGCCCCTCATAAACCTAACCCACCATATCCTGCGTGATACCAACTCTTCCTTTTTTCCCAACTGCTGGGTCTGCTTGTCCACCCGTACCCAGCGCTCCCTAGCGGTCCCAGCTCCTTTGTCCACTTGGACAGACTCACCCATGAAGCTTCACCTCACGTACTCAGTCAAGGCCTTTTCTGGCTCTTATCCCATCACTGACATTGAGAGGCGCCTCCAACTCTTCCACCCGTTGACTGCCTCCTATTCTTTCCACAATCCTGACCGACGGGCTATTGCTTTCCTTCAGCTTGTCAGTTCGACAGGCATATTCCCAATCATCACCCGACTCACCTCTGTGATATATCCTGATAAGGACCGCTTCTTTGAGTCTGCCCAGCGCCCTTTATGGGGACCACTCTTTACTGAGACGCTCCTCATGTCACAGGCTCCGCTCTGCATATCCCGCTCCTTCAAGGTCCCAGCTTACGCCACTTTTGTAGGCACGCTCTCTGCCTCTCTCTGCAACTACACTCTTCATATATCACCTTCCAATAGTCATGTAAACCTAGATCTGTCCACTACCCATCTATTCAAACAGGCAATGAAAAGACCAGATGCCAAATGGAAAAATCCCCTCCGCTTTTCGGGACCTCCCTCTCTAGTCTCCTCAGAACGTTTTTACTATCCATGCCCAACTGACATCAAACACTGTCATACCTCCCCAGCCACTCCCTGGATGCGCTGTCCTCTCTCCCCGTCTGGCACCTGCTATAATCTCACTCTATTTGAAACAGACAATTTAACCCACCCTGTTACTATGTCAGTGAACCCTACCTACTTCAAGCTCAAACTCCAGGACATAGAAACCCTATCCACTCTCCCACTACCAGCCCCTCAAATAGGAGCTGCGCTGTCTGGACAATATTCTGTCTGGGAAAATCAGGTAACTATTCAAGAAAACTGGGGTGTCACCTCAAATACATTCTCCCATCTCCTCACTTTCTCATACTCCTTCTGTCTCAACTCTTCAGGTGTTTTCTTCCTCTGTGGAACATCAACTTACATGTGTCTCCCGGCCAATTGGTCCGGGGTCTGTACCCTTGTCTTCCAATACCCAGACATCGAACTTCTCCCCAATCACCAAACAGTGTCTGTCCCCCTTTTTGCTTCAGTTCGTGCCTCAGCTTCTCACCCAAAGAGGTCCCCTCACCTCTTCCCCTTCCTTGCAGGCCTGGGCATCTCTTCTGCCCTTGGTACTGGTATAGCTGGCTTGGCCTCCTCAACTTTTTATTTCCAGCGGCTTTCGAAGGCTCTTTCGGACACCCTGGATCAAATAGCCGCCTCTGTCACTACGCTCCAGAGCCAAATAGACTCGCTGGCGGGTGTCGTTCTTCAAAACCGCAGGGCGCTGGACCTCATCGCAGCCGAGAAAGGGGGCACCTGTCTCTTTCTCCAAGAAGAGTGCTGCTTCTATGTAAACCAGTCTGGAATAGTCCGAGATGCTGCAAGGAAACTCCGAGAACGAGCATCAGAACTTGGCCAGCATTCTCACTCTTGGGGACAGTGGCCCAATCCTGGATACTGGCTGTCATGGCTGACTCCCTTCCTGGGACCTCTCCTCTTCATTGTCTTCCTATTGACATTTGGGTCTTGTCTGCTTCACTGCCTAACCCGTTTTGTGTCCCGGAGACTTGGCTCCTTTGTCCAAGATGCCACCAAAAGGCATGTGGACAGTATCCTTCAAAATGTCCACTATCAAAGACTGCCCCAAGATGCCCCAACGGGACATAGGGACCCTCAAGACACCGCTCCTGTGTACCAGGGAGAAGTTGGGAGAGCACCAGCGTTGTCCTCCTTACTTTCCAGTTCATACGAAACCAAGTCGGGTGTTAGTCATTGCCACAGTGTTTTGTATCCATCACAATTCCAGAAACGTAATTTTGCCTCCAGAACTAACATTACTCACTTTTCCTGACGGCTGAGACCCGTACCGCTGTCCAAGCGAAACTAGCGGCCGCGTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCATGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGACCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGGACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCCCTCAGCTTTTTTTTTTTTTTTTTTTTGC

**Comment by AJamesPhillips** [comment]
When the algorithm is run now it finds the following:

```
U-fwd primer
position: 891
sequence: TGCCACCTGACGTCTAAGAA

Fwd-1 primer
position: 1300
sequence: GTCTGCTTGTCCACCCGTAC

Fwd-2 primer
position: 1720
sequence: TCTGCCTCTCTCTGCAACTA

Fwd-3 primer
position: 2137
sequence: TCTGTCTGGGAAAATCAGGTAAC

Fwd-4 primer
position: 2560
sequence: ACTACGCTCCAGAGCCAAAT

Fwd-5 primer
position: 2934
sequence: GCATGTGGACAGTATCCTTCAAAA

Fwd-6 primer
position: 3357
sequence: CCGGTATCAGCTCACTCAAAG

Fwd-7 primer
position: 3773
sequence: CTTATCCGGTAACTATCGTCTTGAG

U-rvs primer
position: 3366
sequence: ATTACCGCCTTTGAGTGAGC

Rvs-2 primer
position: 2994
sequence: CTTGAGGGTCCCTATGTCCC

Rvs-3 primer
position: 2781
sequence: CATGACAGCCAGTATCCAGGATTG

Rvs-4 primer
position: 2361
sequence: AAGCAAAAAGGGGGACAGAC

Rvs-5 primer
position: 1997
sequence: GGGTGGGTTAAATTGTCTGTTTCAA

Rvs-6 primer
position: 1577
sequence: TCAAAGAAGCGGTCCTTATCAG

Rvs-7 primer
position: 1157
sequence: CCAAAGGCAGATCATCATCACTT

Rvs-8 primer
position: 737
sequence: TGGATATACCACCGTTGATATATCCC

Rvs-9 primer
position: 318
sequence: ATCCCTGGGTGAGTTTCACC
```

**Comment by AJamesPhillips** [comment]
Fixed with:  https://github.com/Synbiota/GENtle2/tree/issue-194
