### ISSUE TITLE
Wrong sticky ends displayed for sequence generated by RDP part creation process

### ISSUE THREAD

**Issue by depha** [Synbiota/GENtle2#205]
[Example SYBIL file](https://gist.github.com/depha/8e6e8d9b780f45696d24)

![image](https://cloud.githubusercontent.com/assets/961573/8352766/f6b41056-1b37-11e5-9b21-ddc10d5d3888.png)

![image](https://cloud.githubusercontent.com/assets/961573/8352819/4d662b14-1b38-11e5-8f79-f2a1589f1cd6.png)

**Comment by DesireeSy** [comment]
Hey, @depha -- how did you attach the SYBIL file? Every time I try to attach one, I get an error message saying I can only attach images.

**Comment by AJamesPhillips** [comment]
Fixed with: https://github.com/Synbiota/GENtle2/commit/c07d5a4cea09111e8c105202f1493308be1c87f8
