### ISSUE TITLE
Encoding error for en-dashes on primer screens

### ISSUE THREAD

**Issue by DesireeSy** [Synbiota/GENtle2#210]
Anywhere there's something that looks like this:
![image](https://cloud.githubusercontent.com/assets/7390644/8500487/a69d71aa-216a-11e5-91a4-29a7cd4a50d6.png)

(PCR primer tool, sequencing tool, oligo-based RDP parts)

anywhere there's supposed to be an en-dash, there's junk text instead.

This showed up only a day or two ago.

**Comment by depha** [comment]
Fixed by 598c4044ec657e9a89ca9a62bf89efad9847043a.

Deployed on gentle-nightly. Can you please confirm @DesireeSy ? Thanks

**Comment by DesireeSy** [comment]
@alexandremeunier Kind of a stupid question, but I can't figure out how to close issues.

**Comment by DesireeSy** [comment]
S'okay, @OkayDave explained this.
