### ISSUE TITLE
Deletion of last codon in PCR primer when converting an RDP CDS part without a stop codon

### ISSUE THREAD

**Issue by wujpatrick** [Synbiota/GENtle2#212]
Consider this file: https://drive.google.com/open?id=0ByXvyYl_LHxpS1ZJOGVpUTc5QW8

Note that the last codon (Asn, AAC) is not present but the second-last codon (Lys, AAA) is still there.

![capture](https://cloud.githubusercontent.com/assets/11687043/8577604/0860ad30-2567-11e5-87a5-9e7b03d36851.PNG)

I suspect it's because the source sequence for this part already had the stop codon deleted: https://drive.google.com/open?id=0ByXvyYl_LHxpYnowNHhVb3NJN3M

**Comment by DesireeSy** [comment]
Not sure if this is you or if it's James.

**Comment by AJamesPhillips** [comment]
No it's because the part is already an RDP part... or at least it already has stickyEnds.  We currently haven't tried handling the case where someone drags in a part which is already an RDP part / already has stickyEnds.

**Comment by DesireeSy** [comment]
Patrick, are they trying to build a composite part?

If so, we need to cover this use case separately for designer.

**Comment by AJamesPhillips** [comment]
In the RDP PCR window.  If you choose bases 12 to 842 it behaves as expected.

![edited_luxr_circuit_07-jul-2015-rdp-rdp___gentle](https://cloud.githubusercontent.com/assets/526509/8578071/6c2d4f52-25a4-11e5-99c2-79c85e8e9051.png)

**Comment by AJamesPhillips** [comment]
Please reopen if I've missed anything.

**Comment by wujpatrick** [comment]
Yes, this is a composite part. It is a promoter-RBS-CDS.

They removed the stop codon in their source sequence prior to the creation
of primers. GENtle added a start codon and made the end a C. However, the
final codon disappears. It's not intended.

Patrick Wu
Sales and Account Manager
www.synbiota.com

**Comment by AJamesPhillips** [comment]
When you can, could you run me through the sets to recreate this behaviour please?  If you follow my steps above you obviously don't get the error you're referring to.  If I try to just create a new RDP part from the sequence posted, without changing the `from` and `to` values, I can't because the sequence is not a multiple of 3.

**Comment by AJamesPhillips** [comment]
```
<sybil>
<session>
<circuit>
<sequence type="dna" name="Edited LuxR Circuit 07-Jul-2015" circular="false">ACCTGTAGGATCGTACAGGTTTACGCAAGAAAATGGTTTGTTATAGTCGAATAAATACTAGAGAAAGAGGAGAAATACTAGATGAAAAACATAAATGCCGACGACACATACAGAATAATTAATAAAATTAAAGCTTGTAGAAGCAATAATGATATTAATCAATGCTTATCTGATATGACTAAAATGGTACATTGTGAATATTATTTACTCGCGATCATTTATCCTCATTCTATGGTTAAATCTGATATTTCAATCCTAGATAATTACCCTAAAAAATGGAGGCAATATTATGATGACGCTAATTTAATAAAATATGATCCTATAGTAGATTATTCTAACTCCAATCATTCACCAATTAATTGGAATATATTTGAAAACAATGCTGTAAATAAAAAATCTCCAAATGTAATTAAAGAAGCGAAAACATCAGGTCTTATCACTGGGTTTAGTTTCCCTATTCATACGGCTAACAATGGCTTCGGAATGCTTAGTTTTGCACATTCAGAAAAAGACAACTATATAGATAGTTTATTTTTACATGCGTGTATGAACATACCATTAATTGTTCCTTCTCTAGTTGATAATTATCGAAAAATAAATATAGCAAATAATAAATCAAACAACGATTTAACCAAAAGAGAAAAAGAATGTTTAGCGTGGGCATGCGAAGGAAAAAGCTCTTGGGATATTTCAAAAATATTAGGTTGCAGTGAGCGTACTGTCACTTTCCATTTAACCAATGCGCAAATGAAACTCAATACAACAAACCGCTGCCAAAGTATTTCTAAAGCAATTTTAACAGGAGCAATTGATTGCCCATACTTTAAAAAT</sequence>
</circuit>
</session>
</sybil>
```

If you try to make a part out of this sequence the trailing AAC (converted from AAT) is dropped.
