### ISSUE TITLE
Edit Sequence: Fix all BsaI/NotI sites button is enabled on sequences where there are no BsaI/NotI sites

### ISSUE THREAD

**Issue by heathermmm** [Synbiota/GENtle2#215]
Fix all Bsa1/Not1 sites button should display but be disabled if there are sites other than BsaI or NotI (XbaI, etc.) sites on the sequence. 

Using: http://gentle.s3.amazonaws.com/test-designer/assets/index.html and Nightly

**Comment by heathermmm** [comment]
cc @DesireeSy

**Comment by MasonEdwards** [comment]
fixed by 4b7304b92f997abb31db39e7766f03fbef5fa123
