### ISSUE TITLE
"Could not parse the sequence" error when loading multiple files to gentle-beta

### ISSUE THREAD

**Issue by wujpatrick** [Synbiota/GENtle2#216]
e.g. SYBIL files in this Dropbox folder: https://www.dropbox.com/sh/5grmbkw6juwxxzc/AAD6LmTdYjIDJ3Egjd0avxRKa?dl=0

When I attempt to open a new sequence from gentle-beta and select multiple SYBIL files, I will get this error message:

![parse1](https://cloud.githubusercontent.com/assets/11687043/8703806/7c3f469c-2adc-11e5-80d5-cf8b9fe6456d.png)

When I click away the error message, another one pops up for each item that I attempt to upload:

![parse2](https://cloud.githubusercontent.com/assets/11687043/8703813/8c20a4ca-2adc-11e5-9055-1ccb52d7617f.png)

However, as you can see, there is nothing that appears to be wrong with the sequence files after these errors pop up.

**Comment by wujpatrick** [comment]
Correction: some files seem to evade the issue. See "x-AraC-z'.sybil" and "x-LacI-z'.sybil" under the "Regulators" folder for example.

**Comment by depha** [comment]
Fixed in 503f15f4645b060c5ba9617713c775854921fe25
