### ISSUE TITLE
Top Nav bar in "Designer" is different than DNA editor

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#28]
What happened: After loading multiple parts into Gentle and entering "Designer", some of the options in the top nav bar are no longer needed.

What should happen: After entering "Designer", a "Designer" specific Nav bar should be present: 1) "Sequence" is no longer needed; 2) "gear icon" is not needed; 3) "sequence info [little i icon]" is not needed; 4) "expand/collapse context" arrow icon is not needed

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
