### ISSUE TITLE
Designer: Make parts draggable on Mobile (iOS/Android)

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#31]
What happened: When I have a loaded sequence/sequences in designer I try to drag them into the top work-space, but they are not draggable

What should happen: The parts should all be draggable (just like in the PC/desktop version)

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).

Also fixed in new app.
