### ISSUE TITLE
Designer: Scrollable top work-box - Desktop and Mobile

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#32]
What happened: When I load many 'parts' into the top work-box in designer, once the screen is filled from left to right, the graphic then continues on a second line. When the second line is filled, I can no longer add parts.

What should happen: The top work-box should be scrollable and the parts should only be in only one line. This scrollable feature should be functional on both desktop and mobile

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
