### ISSUE TITLE
Draggable Context window in Context box - Mobile fix

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#33]
What happened: In the desktop version you can click and drag the yellow highlighted region of the context window to navigate to a new position. This is inactive on Mobile

What should happen: This feature should be active on mobile (iOS and Android)

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
