### ISSUE TITLE
Find sequence feature highlight lost when scrolling: mobile

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#38]
What happened: when I use the search feature to find a sequence and then click on one of the suggested regions, that sequence is highlighted in yellow. If I touch the screen or try to scroll, the yellow disappears and I lose the spot.

What should happen: I should be able to scroll up and down whilst the sequences stays highlighted. Perhaps a double touch should remove the highlighting

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
