### ISSUE TITLE
Annotation feature : access/edit annotation description

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#41]
What happens: after part of the sequence is annotated and the description and title are saved, the annotation can be Only be deleted in the "sequence info --> annotation tab"

What should happen: the user should also be able to edit That annotation (title, description) via the Sequence info dialogue

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
