### ISSUE TITLE
Saving Versions of .SYBIL files rather than writing new ones (beginnig of versioning!)

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#48]
What happened: The user created a new sequence within a project in Gentle and pressed 'save to synbiota'. The user then changed the name/description of the sequence and saved to synbiota. This resulted in two sequences appearing in their project. Once "un named" sequence and one "named (with the changes they made)". Every new save results in a new sequence in the user's Synbiota projects section.

What should happen: The user should create a sequence and all changes and saves to that sequence should result in only one sequence visible in the projects. Other saves to synbiota could be saved as versions. This suggests the need to have a "Saved Versions" button next to the sequence in the project that, when clicked, results in a popup with clickable ["name" "date/time edited" "edited by user"] links. When clicked this opens that version in gentle.

This problem is treading on Versioning territory! 

Brian are your free to start tackling the versioning?? Przemek, is there an easy fix for now?? Magnus, any thoughts??

@magnusmanske @szeryf

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
