### ISSUE TITLE
Warning to Save un-saved sequences

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#50]
What happened: When the user closed the Gentle tab, or when Gentle launches and closes old sequences, old work can be lost. (e.g. the user didn't think about whether they saved to synbiota. Their data could have been lost.)

What should happen: If the user closes the browser for gentle, or changes the url (e.g. someone searches google or something), there should be a warning the comes up saying: "Sequences have been modified. Save changes to Synbiota?" with three buttons: [Don't Save], [Save], [Save All]. 

For non-synbiota version: "Sequences have been modified. Download your changes to local?" This would automatically export the unsaved file as a .sybil file to local downloads

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
