### ISSUE TITLE
Name of sequence on Browser tab

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#56]
What happens: Presently the name of the sequence is visible in the bottom right corner of the Gentle2 window. 

What could happen: The name of the sequence could also be present in browser tab (title tag). Something like "Gentle2 - [sequence name]"

This would update dynamically if the user decided to change the name of the sequence

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).

Fixed in new app.
