### ISSUE TITLE
Optimize Copy/Cut/Paste feature

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#6]
There is room for optimization of the copy/cut/paste feature in Gentle (especially for mobile).

What you did: Tried to copy/paste some DNA code using the copy/paste function on mobile.

What did happen: I select some code to copy/cut and click on file --> copy and a dialogue opens showing the code I selected. I close the dialogue, choose a point to paste the code into (double click into edit mode) and click file--> paste, a dialogue with the 'paste' code opens, but it is blank. Ideally, this would have the code I just copied, so I can simply click paste.

What should happen: Ideally, there isn't any dialogue that appears and the copy/paste is done behind the scenes - it is a standard copy/paste function. (the shortcut keys work on laptop/desktop, but unfortunately this doesn't work on mobile!

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
