### ISSUE TITLE
Beautify the context box

### ISSUE THREAD

**Issue by jpahara** [Synbiota/GENtle2#60]
Presently the context box is all about functionality and it works great (on desktop - see issue #XX for mobile issues). As we continue to build out and refine the user interface the context box is a key feature that requires revamping. This is completely up for discussion, however, some suggested features are below:

1) limit the width of the context box based upon annotations actively used. For example, presently the context box is wide enough to showcase annotations for coding_sequences, notes, genes, etc. If only coding_sequences and notes annotations are present in the, the width of the context box should scale to needed width
2) the numbers in the context box could be abbreviated to save space, for example: 5,000 --> 5k

also see #36

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
