### ISSUE TITLE
bugs of Synbiota web app on iOS devices

### ISSUE THREAD

**Issue by Leukippos** [Synbiota/GENtle2#63]
I opened and found following issues on iOS devices:
1 JavaScript: Error undefined QUOTA_EXCEEDED_ERR_DOM Exeption 22 An attemp was made to add something to the storage
2 The user interface do not adapt to the device, needs to be optimized, picture and text overlap, UI really messy 
3 menue is missing
4 pages need to be scaled
5 viewport needs to be customized 
6 such as input behavior, app reacts very slowly
7 network performance need to be optimized

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
