### ISSUE TITLE
Link to plugins.js is broken

### ISSUE THREAD

**Issue by c0nn0r** [Synbiota/GENtle2#68]
On the "About Plugins" page for GENtle (http://ec2-23-20-169-157.compute-1.amazonaws.com/dev/public/templates/help.html#plugins) there is a link to plugins.js that is broken (404).

The bad URL is: http://ec2-23-20-169-157.compute-1.amazonaws.com/plugins.js

The correct URL should be: http://ec2-23-20-169-157.compute-1.amazonaws.com/dev/plugins.js

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
