### ISSUE TITLE
Plasmid Map Small Annotation Labels

### ISSUE THREAD

**Issue by bkevinchen** [Synbiota/GENtle2#87]
See image below. This would be an issue for labels on small domains.

![screenshot from 2013-06-04 01 40 09](https://f.cloud.github.com/assets/4379930/603786/47b446ec-ccd9-11e2-94c5-7d2f6ae33a23.png)

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
