### ISSUE TITLE
[test] Saved Date Not Updating

### ISSUE THREAD

**Issue by bkevinchen** [Synbiota/GENtle2#96]
What happened:
Started Synbiota --> Opened Gentle --> opened previous sequence --> created a new sequence --> Saved new sequence and last saved date stayed at "UNSAVED" even though it does appear in my Synbiota storage

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
