### ISSUE TITLE
[test] base pair count only updates when sequence is saved to synbiota, or reloaded

### ISSUE THREAD

**Issue by bkevinchen** [Synbiota/GENtle2#98]
What happened: The basepair count at the top of the page should probably update live. At the moment it only seems to update if I save the sequence to synbiota or if I switch to a different sequence, and then switch back.

**Comment by depha** [comment]
Closing issue because it applies to the [legacy app](https://github.com/Synbiota/GENtle2/tree/legacy_app/master).
